name: Deploy Frontend Preview to GitHub Pages

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # 使用项目兼容的 Node.js 版本

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Vue.js project
        working-directory: ./frontend
        run: npx vite build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          # CNAME: example.com # 如果您有自定义域名，可以在这里配置
